disruptors:
    node_disruptor:
       # Controller where all control plane are combined in one node (common case)
       allinone_ controller:
           role : controller

       # All in one controller with seperate network node(common case)
       allinone_controller_1:
           role: controller_1

       # Below options define where each service is running on seperate node
       # If this does not fit use custom controller option
       rabbitmq_controller:
           role : rabbit
       galera_controller:
           role:  mysql
       haproxy_controller:
           role:  haproxy
       keystone_controller:
           role:  keystone
       glance_controller:
           role:  glance
       network_controller:
           role : network
       neutron_controller:
           role : neutron_api
       nova_controller:
           role: nova
       cinder_controller:
           role: cinder
       horizon_controller:
           role: horizon
       compute_node:
           role: compute

       # Where specific services are running in a controller
       custom_controller:
           role: nova, cinder
 
    container_disruptor:
       keystone_container:
           container_name: docker-keystone.service
           role: controller
           disruption: finite
       neutron_api_container:
           container_name : docker-neutronsrv.service 
           role : controller
           disruption: finite
       nova_api_container:
           container_name: docker-novaapi.service 
           role : controller
           disruption: finite
       nova_scheduler_container:
           container_name : docker-novasch.service 
           role : controller
           disruption: finite
       novncproxy_container:
           container_name : docker-novanovncproxy.service 
           role : controller
           disruption: finite
       novaconsole_container:
           container_name : docker-novaconsoleauth.service 
           role : controller
           disruption: finite
       novaconductor_container:
           container_name : docker-novacond.service 
           role : controller
           disruption: finite
       cinder_volume_container:
           container_name : docker-cindervolume.service  
           role : controller
           disruption: finite
       cinder_scheduler_container:
           container_name : docker-cindersch.service 
           role : controller
           disruption: finite
       cinder_api_container:
           container_name : docker-cinderapi.service 
           role : controller
           disruption: finite
       metadata_container:
           container_name : docker-neutronmeta.service 
           role : controller
           disruption: finite
       linuxbridge_cintainer:
           container_name : docker-neutronlb.service 
           role : controller
           disruption: finite
       l3agent_container:
           container_name : docker-neutronl3.service 
           role : controller
           disruption: finite
       dhcp_agent_container:
           container_name : docker-neutrondhcp.service 
           role : controller
           disruption: finite
       glance_api_container:
           container_name : docker-glanceapi.service 
           role : controller
           disruption: finite
       glance_registry_controller:
           container_name : docker-glancer.service 
           role : controller
           disruption: finite
       rabbit_container:
           container_name : docker-rabbitmq.service  
           role : controller
           disruption: finite
       mariadb_container:
           container_name : docker-mariadb.service 
           role : controller
           disruption: finite
       haproxy_container:
           container_name : docker-haproxy.service 
           role : controller
           disruption: finite
        

    process_disruptor:
       nova_api:
           process_name : openstack-nova-api.service
           role : controller
           type : graceful
       keystone_api:
           process_name: httpd
           role : controller
           type : graceful
       neutron_api:
           process_name : neutron-server.service
           role: controller
           type: graceful
       rabbitmq_api:
           process_name: rabbitmq-server
           role: controller
           type: graceful
       glance_api:
           process_name: openstack-glance-api.service
           role: controller
           type: graceful
       glance_registry:
           process_name: openstack-glance-registry
           role: controller
           type: graceful
       nova_novnc:
           process_name: openstack-nova-novncproxy
           role : controller
           type: graceful
       nova_conductor:
           process_name : openstack-nova-conductor
           role: controller
           type: graceful
       nova_scheduler:
           process_name: openstack-nova-scheduler.service
           role : controller
           type: graceful
       dhcp_agent:
           process_name: neutron-dhcp-agent
           role : controller
           type: graceful
       ovs_agent:
           process_name: neutron-openvswitch-agent
           role : controller
           type: graceful
       neutron_metadata:
           process_name: neutron-metadata-agent
           role: controller
           type: graceful
       neutron_l3:
           process_name: neutron-l3-agent
           role : controller
           type: graceful
       nova_compute:
           process_name : openstack-nova-compute
           role : compute
           type: graceful
    vm_disruptor:
         glance_node: 
            name: ['svl6-csl-b-glancectl-003']
            type: api
            role: controller
         neutron_node:
            name: ['svl6-csl-b-neutronapi-001']
            type: api
            role: controller
    jump_host_disruptor:
         cinder_node:
            name: ['svl6-csl-b-glancectl-002']
            role: jump-host

    jump_host_process_disruptor:
         glance_api:
            node: ['svl6-csl-b-glancectl-002']
            process_name: openstack-glance-api
            role: jump-host
            type: graceful


